/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesNewRouteImport } from './routes/packages.new'
import { Route as PackagesIdRouteImport } from './routes/packages.$id'
import { Route as PackagesIdValidateRouteImport } from './routes/packages.$id.validate'
import { Route as PackagesIdPlanRouteImport } from './routes/packages.$id.plan'
import { Route as PackagesIdIngestRouteImport } from './routes/packages.$id.ingest'
import { Route as PackagesIdHitlRouteImport } from './routes/packages.$id.hitl'
import { Route as PackagesIdFile2RouteImport } from './routes/packages.$id.file2'
import { Route as PackagesIdFile1RouteImport } from './routes/packages.$id.file1'
import { Route as PackagesIdExceptionsRouteImport } from './routes/packages.$id.exceptions'
import { Route as PackagesIdCompleteRouteImport } from './routes/packages.$id.complete'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesNewRoute = PackagesNewRouteImport.update({
  id: '/packages/new',
  path: '/packages/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIdRoute = PackagesIdRouteImport.update({
  id: '/packages/$id',
  path: '/packages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIdValidateRoute = PackagesIdValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => PackagesIdRoute,
} as any)
const PackagesIdPlanRoute = PackagesIdPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => PackagesIdRoute,
} as any)
const PackagesIdIngestRoute = PackagesIdIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => PackagesIdRoute,
} as any)
const PackagesIdHitlRoute = PackagesIdHitlRouteImport.update({
  id: '/hitl',
  path: '/hitl',
  getParentRoute: () => PackagesIdRoute,
} as any)
const PackagesIdFile2Route = PackagesIdFile2RouteImport.update({
  id: '/file2',
  path: '/file2',
  getParentRoute: () => PackagesIdRoute,
} as any)
const PackagesIdFile1Route = PackagesIdFile1RouteImport.update({
  id: '/file1',
  path: '/file1',
  getParentRoute: () => PackagesIdRoute,
} as any)
const PackagesIdExceptionsRoute = PackagesIdExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => PackagesIdRoute,
} as any)
const PackagesIdCompleteRoute = PackagesIdCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => PackagesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/packages/$id': typeof PackagesIdRouteWithChildren
  '/packages/new': typeof PackagesNewRoute
  '/packages/$id/complete': typeof PackagesIdCompleteRoute
  '/packages/$id/exceptions': typeof PackagesIdExceptionsRoute
  '/packages/$id/file1': typeof PackagesIdFile1Route
  '/packages/$id/file2': typeof PackagesIdFile2Route
  '/packages/$id/hitl': typeof PackagesIdHitlRoute
  '/packages/$id/ingest': typeof PackagesIdIngestRoute
  '/packages/$id/plan': typeof PackagesIdPlanRoute
  '/packages/$id/validate': typeof PackagesIdValidateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/packages/$id': typeof PackagesIdRouteWithChildren
  '/packages/new': typeof PackagesNewRoute
  '/packages/$id/complete': typeof PackagesIdCompleteRoute
  '/packages/$id/exceptions': typeof PackagesIdExceptionsRoute
  '/packages/$id/file1': typeof PackagesIdFile1Route
  '/packages/$id/file2': typeof PackagesIdFile2Route
  '/packages/$id/hitl': typeof PackagesIdHitlRoute
  '/packages/$id/ingest': typeof PackagesIdIngestRoute
  '/packages/$id/plan': typeof PackagesIdPlanRoute
  '/packages/$id/validate': typeof PackagesIdValidateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/packages/$id': typeof PackagesIdRouteWithChildren
  '/packages/new': typeof PackagesNewRoute
  '/packages/$id/complete': typeof PackagesIdCompleteRoute
  '/packages/$id/exceptions': typeof PackagesIdExceptionsRoute
  '/packages/$id/file1': typeof PackagesIdFile1Route
  '/packages/$id/file2': typeof PackagesIdFile2Route
  '/packages/$id/hitl': typeof PackagesIdHitlRoute
  '/packages/$id/ingest': typeof PackagesIdIngestRoute
  '/packages/$id/plan': typeof PackagesIdPlanRoute
  '/packages/$id/validate': typeof PackagesIdValidateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contracts'
    | '/reports'
    | '/settings'
    | '/packages/$id'
    | '/packages/new'
    | '/packages/$id/complete'
    | '/packages/$id/exceptions'
    | '/packages/$id/file1'
    | '/packages/$id/file2'
    | '/packages/$id/hitl'
    | '/packages/$id/ingest'
    | '/packages/$id/plan'
    | '/packages/$id/validate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contracts'
    | '/reports'
    | '/settings'
    | '/packages/$id'
    | '/packages/new'
    | '/packages/$id/complete'
    | '/packages/$id/exceptions'
    | '/packages/$id/file1'
    | '/packages/$id/file2'
    | '/packages/$id/hitl'
    | '/packages/$id/ingest'
    | '/packages/$id/plan'
    | '/packages/$id/validate'
  id:
    | '__root__'
    | '/'
    | '/contracts'
    | '/reports'
    | '/settings'
    | '/packages/$id'
    | '/packages/new'
    | '/packages/$id/complete'
    | '/packages/$id/exceptions'
    | '/packages/$id/file1'
    | '/packages/$id/file2'
    | '/packages/$id/hitl'
    | '/packages/$id/ingest'
    | '/packages/$id/plan'
    | '/packages/$id/validate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContractsRoute: typeof ContractsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  PackagesIdRoute: typeof PackagesIdRouteWithChildren
  PackagesNewRoute: typeof PackagesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/new': {
      id: '/packages/new'
      path: '/packages/new'
      fullPath: '/packages/new'
      preLoaderRoute: typeof PackagesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$id': {
      id: '/packages/$id'
      path: '/packages/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof PackagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$id/validate': {
      id: '/packages/$id/validate'
      path: '/validate'
      fullPath: '/packages/$id/validate'
      preLoaderRoute: typeof PackagesIdValidateRouteImport
      parentRoute: typeof PackagesIdRoute
    }
    '/packages/$id/plan': {
      id: '/packages/$id/plan'
      path: '/plan'
      fullPath: '/packages/$id/plan'
      preLoaderRoute: typeof PackagesIdPlanRouteImport
      parentRoute: typeof PackagesIdRoute
    }
    '/packages/$id/ingest': {
      id: '/packages/$id/ingest'
      path: '/ingest'
      fullPath: '/packages/$id/ingest'
      preLoaderRoute: typeof PackagesIdIngestRouteImport
      parentRoute: typeof PackagesIdRoute
    }
    '/packages/$id/hitl': {
      id: '/packages/$id/hitl'
      path: '/hitl'
      fullPath: '/packages/$id/hitl'
      preLoaderRoute: typeof PackagesIdHitlRouteImport
      parentRoute: typeof PackagesIdRoute
    }
    '/packages/$id/file2': {
      id: '/packages/$id/file2'
      path: '/file2'
      fullPath: '/packages/$id/file2'
      preLoaderRoute: typeof PackagesIdFile2RouteImport
      parentRoute: typeof PackagesIdRoute
    }
    '/packages/$id/file1': {
      id: '/packages/$id/file1'
      path: '/file1'
      fullPath: '/packages/$id/file1'
      preLoaderRoute: typeof PackagesIdFile1RouteImport
      parentRoute: typeof PackagesIdRoute
    }
    '/packages/$id/exceptions': {
      id: '/packages/$id/exceptions'
      path: '/exceptions'
      fullPath: '/packages/$id/exceptions'
      preLoaderRoute: typeof PackagesIdExceptionsRouteImport
      parentRoute: typeof PackagesIdRoute
    }
    '/packages/$id/complete': {
      id: '/packages/$id/complete'
      path: '/complete'
      fullPath: '/packages/$id/complete'
      preLoaderRoute: typeof PackagesIdCompleteRouteImport
      parentRoute: typeof PackagesIdRoute
    }
  }
}

interface PackagesIdRouteChildren {
  PackagesIdCompleteRoute: typeof PackagesIdCompleteRoute
  PackagesIdExceptionsRoute: typeof PackagesIdExceptionsRoute
  PackagesIdFile1Route: typeof PackagesIdFile1Route
  PackagesIdFile2Route: typeof PackagesIdFile2Route
  PackagesIdHitlRoute: typeof PackagesIdHitlRoute
  PackagesIdIngestRoute: typeof PackagesIdIngestRoute
  PackagesIdPlanRoute: typeof PackagesIdPlanRoute
  PackagesIdValidateRoute: typeof PackagesIdValidateRoute
}

const PackagesIdRouteChildren: PackagesIdRouteChildren = {
  PackagesIdCompleteRoute: PackagesIdCompleteRoute,
  PackagesIdExceptionsRoute: PackagesIdExceptionsRoute,
  PackagesIdFile1Route: PackagesIdFile1Route,
  PackagesIdFile2Route: PackagesIdFile2Route,
  PackagesIdHitlRoute: PackagesIdHitlRoute,
  PackagesIdIngestRoute: PackagesIdIngestRoute,
  PackagesIdPlanRoute: PackagesIdPlanRoute,
  PackagesIdValidateRoute: PackagesIdValidateRoute,
}

const PackagesIdRouteWithChildren = PackagesIdRoute._addFileChildren(
  PackagesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractsRoute: ContractsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  PackagesIdRoute: PackagesIdRouteWithChildren,
  PackagesNewRoute: PackagesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
